### ISSUE TITLE
NoMethodError: undefined method `acts_as'

### ISSUE THREAD

**Issue by Bongs** [hzamani/acts_as_relation#20]
I followed the documentation and have following model in my application

```
class Contest < ActiveRecord::Base
  belongs_to :category
  acts_as_superclass
  attr_accessible :title, :description, :category_id
end

class Quiz < ActiveRecord::Base
  acts_as :contest
end
```

Contest on console

```
1.9.3p125 :009 > Contest
 => Contest(id: integer, as_contest_id: integer, as_contest_type: string, title: string, description: text, category_id: integer, created_at: datetime, updated_at: datetime)
```

When I checked for Quiz on console I get following error

```
NoMethodError: undefined method `acts_as' for Quiz(id: integer, created_at: datetime, updated_at: datetime):Class
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.1/lib/active_record/dynamic_matchers.rb:50:in `method_missing'
    from /home/saurabh/Desktop/Projects/c2w/app/models/quiz.rb:2:in `<class:Quiz>'
    from /home/saurabh/Desktop/Projects/c2w/app/models/quiz.rb:1:in `<top (required)>'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:469:in `load'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:469:in `block in load_file'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:639:in `new_constants_in'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:468:in `load_file'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:353:in `require_or_load'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:502:in `load_missing_constant'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:192:in `block in const_missing'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:190:in `each'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:190:in `const_missing'
    from (irb):15
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.1/lib/rails/commands/console.rb:47:in `start'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.1/lib/rails/commands/console.rb:8:in `start'
    from /home/saurabh/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.1/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

What did I miss?

**Comment by Bongs** [comment]
Oops sorry... There is nothing wrong in implementation. I had to restart the console... :D It is working like charm :)

**Comment by hzamani** [comment]
:)
