### ISSUE TITLE
Trying to use acts_as_relation and getting unexpected results.

### ISSUE THREAD

**Issue by derrelldurrett** [hzamani/acts_as_relation#26]
I have the following relationships via `acts_as_relation`:

``` ruby
class Node < ActiveRecord::Base
  acts_as_superclass
  belongs_to :game, polymorphic: true
  #...
end

class Game < ActiveRecord::Base
  acts_as :node
  has_many :ancestors, class_name: 'Node',
           foreign_key: 'ancestor_id'
  #...
end

class Team < ActiveRecord::Base
  acts_as :node
  # ...
end
```

When I add a `Game` to the list of `ancestors` in another `Game`, I get:

``` ruby
ActiveRecord::AssociationTypeMismatch: Node(#30169720) expected, got Game(#24699180)
/home/rev/.rvm/gems/ruby-1.9.3-p385@global/gems/activerecord-3.2.12/lib/active_record/associations/association.rb:204:in `raise_on_type_mismatch'
/home/rev/.rvm/gems/ruby-1.9.3-p385@global/gems/activerecord-3.2.12/lib/active_record/associations/collection_association.rb:494:in `block in concat_records'
/home/rev/.rvm/gems/ruby-1.9.3-p385@global/gems/activerecord-3.2.12/lib/active_record/associations/collection_association.rb:493:in `each'
/home/rev/.rvm/gems/ruby-1.9.3-p385@global/gems/activerecord-3.2.12/lib/active_record/associations/collection_association.rb:493:in `concat_records'
/home/rev/.rvm/gems/ruby-1.9.3-p385@global/gems/activerecord-3.2.12/lib/active_record/associations/collection_association.rb:132:in `concat'
/home/rev/.rvm/gems/ruby-1.9.3-p385@global/gems/activerecord-3.2.12/lib/active_record/associations/collection_proxy.rb:116:in `<<'
/home/rev/RubymineProjects/AliasMadness/app/models/bracket_factory.rb:17:in `block in create_bracket'
```

If I examine the Game object in the debugger, `object.is_a? Node` returns `false`, which makes no sense, given the above.

Do you have any suggestions for how I can proceed? This is rails 3.2.12 under ruby 1.9.3.

**Comment by hzamani** [comment]
A game is a node an belongs to another node? Even if this is the case,
polymorphic makes no sense. We usually don't use a model name as a
polymorphic relation name.

This was what I got on the first look. I am going on a trip with no
internet access, so next reply will be on next week!

**Comment by derrelldurrett** [comment]
![Nodes 1 ](https://f.cloud.github.com/assets/2601451/260091/2921b91c-8cce-11e2-85b4-635713d95ffb.jpg)

So, yes, Games belong to and are Nodes. Teams are also Nodes. Games 1) must have two "ancestors", which can be either a Game or a Team, 2) eventually have another Team (which relationship is not shown for purposes of clarity).

Part of your comment doesn't make much sense to me (which suggests I'm doing something wrong): "We don't usually use a model name as a polymorphic relation name." I went through several iterations of code attempting to get a working relationship, and what you see above was the version that managed to get through the compile step.

Previous attempts included this combination:

``` ruby
class Node < ActiveRecord::Base
  acts_as_superclass
  belongs_to :ancestor, polymorphic: true
  # ...
end

class Game < ActiveRecord::Base
  acts_as :node
  has_many :nodes, as: :ancestor
  # ...
end
```

Those would fail because `ancestors` wasn't a method on a `Game` object.

**Comment by hzamani** [comment]
Maybe it's to late! But why `polymorphic: true` is there?

**Comment by derrelldurrett** [comment]
Not too late (I'm always looking to understand what I missed the first time through).

In the earlier attempt, I was trying to express the relationship that Nodes, being the superclass, were potentially either Games or Teams.

I've been away from this for some time. So, if I'm saying something incomprehensible, it may be a lack of memory or a genuine lack of understanding something. If you could be more verbose and explicit, that would be helpful.
