### ISSUE TITLE
Gem dependencies incorrect

### ISSUE THREAD

**Issue by icem** [hzamani/acts_as_relation#85]
I'm trying to use acts_as_relation outside of rails. Gem dependencies specified only activerecord gem. But then during load I get 

```
uninitialized constant ActiveSupport::Concern
/Users/icem/.rvm/gems/ruby-2.1.4@async-workers/gems/acts_as_relation-1.1.3/lib/active_record/acts_as_relation.rb:3:in `<module:ActsAsRelation>'
/Users/icem/.rvm/gems/ruby-2.1.4@async-workers/gems/acts_as_relation-1.1.3/lib/active_record/acts_as_relation.rb:2:in `<module:ActiveRecord>'
/Users/icem/.rvm/gems/ruby-2.1.4@async-workers/gems/acts_as_relation-1.1.3/lib/active_record/acts_as_relation.rb:1:in `<top (required)>'
/Users/icem/.rvm/gems/ruby-2.1.4@async-workers/gems/acts_as_relation-1.1.3/lib/acts_as_relation.rb:1:in `require'
/Users/icem/.rvm/gems/ruby-2.1.4@async-workers/gems/acts_as_relation-1.1.3/lib/acts_as_relation.rb:1:in `<top (required)>'
```

Obviously if you use Concern you should depend on activesupport also.

**Comment by icem** [comment]
Oops, I was wrong because activerecord already requires activesupport.
